### ISSUE TITLE
Implement Category Endpoint

### ISSUE THREAD

**Issue by Shehanka** [codekittyshow/code-kitty-api#1]
# Implement Category Endpoint
All **Create, Read, Update, Delete** endpoints need to be implemented.

1. Clone the repo
2. Go to [Mongo DB Cloud](https://cloud.mongodb.com) and create a Database
3. Create a `.env` file in the root directory
4. Add Below lines in `.env` file<br/>
   ```PORT=4000``` <br/>
   ```MONGO_DB_URI=<YOUR MONGO DB URL>```
5. Make CRUD for category
6. Include Postman Screenshots with the Pull Request

**Comment by Mannan2812** [comment]
Hey @Shehanka, I am working on this issue and I want to know is there any specific reason to use mongo client and not mongoose to interact with DB, because if we use mongo client then we have to specify validation rules for the schema but with mongoose, we can do it right away.
